name: .NET Framework Build

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Get NuGet packages
      run: nuget restore PPTXcreator.sln

    - name: Build solution
      run: msbuild PPTXcreator.sln /p:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build files
        path: bin\Release\
        retention-days: 7
